export const SET_SESSION = 'SET_SESSION';
export const CLEAR_SESSION = 'CLEAR_SESSION';
export const SET_EMAIL = 'SET_EMAIL';
export const SET_SHOE_LISTINGS = 'SET_SHOE_LISTINGS';
export const APPEND_SHOE_LISTINGS = 'APPEND_SHOE_LISTINGS';
